export enum TugAction {
  STANDING_UP = "STANDING_UP",
  FIRST_WALK = "FIRST_WALK",
  FIRST_TURN = "FIRST_TURN",
  SECOND_WALK = "SECOND_WALK",
  SECOND_TURN = "SECOND_TURN",
  SITTING_DOWN = "SITTING_DOWN"
}
